# 这是一个用于保存地图的服务定义文件

# 请求部分（系统自动生成的 SaveMapRequest 类的属性）
# 定义要保存地图的文件路径，字符串类型
string file_path  



# 分隔线，用于区分请求和响应部分
---



# 响应部分（系统自动生成的 SaveMapResponse 类的属性）
# 表示地图保存操作是否成功，布尔类型
# true 表示保存成功，false 表示保存失败
bool success      

# 当保存操作失败时，提供详细的错误信息；
# 当保存成功时，可提供一些额外的提示信息，字符串类型
string message  
